### ISSUE TITLE
Occasional error from AWS sdk when ASG does not exist.

### ISSUE THREAD

**Issue by svolpe43** [svolpe43/cfsh#13]
```
/#:ssh volpe-5-2-6/A/i
/Users/shawn.volpe/acquia/rtools/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

TypeError: Cannot read property 'Instances' of undefined
    at Response.<anonymous> (/Users/shawn.volpe/acquia/rtools/lib/nodes.js:145:45)
    at Request.<anonymous> (/Users/shawn.volpe/acquia/rtools/node_modules/aws-sdk/lib/request.js:355:18)
    at Request.callListeners (/Users/shawn.volpe/acquia/rtools/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/shawn.volpe/acquia/rtools/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/shawn.volpe/acquia/rtools/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/Users/shawn.volpe/acquia/rtools/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/shawn.volpe/acquia/rtools/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/shawn.volpe/acquia/rtools/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/shawn.volpe/acquia/rtools/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/shawn.volpe/acquia/rtools/node_modules/aws-sdk/lib/request.js:617:12)

```

**Comment by svolpe43** [comment]
I think this is fixed.
